### ISSUE TITLE
Consider using a more open license

### ISSUE THREAD

**Issue by mastertinner** [matryer/is#13]
Is there a specific reason why this project uses the restrictive GPL 3 license? I for one would be able to use it in a much more relaxed way if it used a more open license like MIT.

@matryer, would you consider switching?

**Comment by matryer** [comment]
I think it was the default for new projects for a time... but I think an MIT license is right.

**Comment by matryer** [comment]
There you go https://github.com/matryer/is/blob/master/LICENSE

**Comment by mastertinner** [comment]
Thanks, @matryer!

**Comment by mastertinner** [comment]
@matryer, would that be possible?
