### ISSUE TITLE
Additional error assertations

### ISSUE THREAD

**Issue by matejb** [matryer/is#16]
Hi, let me first say that the library is great, thank you for creating it!

I find myself repeating few checks for errors that could be made into assertation.
It would be my pleasure to contribute this upgrades if we agree on their form.

1. `is.NoErr(err)` is great but in lots of situations I need to check the opposite, that error is present.
Using `is.True(err != nil)` works but does not have the same approach to assertation.
I suggest adding `is.Err(err)` that would assert `err` is not `nil`. 

2. Usually, I add context to errors but I do not use custom error types as there is no behavior associated with this errors. When I have this situation, I would like to check that error contains a particular substring.
I suggest adding `is.ErrContains(err, "part of error message")` that would assert if error contains given substring.

What do you think about this two additions?

**Comment by matryer** [comment]
Thanks for your comments.

To be honest, I don't think these are common enough problems to warrant inclusion in the package. It's clearer to say `is.True(strings.Contains(err.Error(), "some error message"))` if you want to.

Tests matching strings can also fail when the tests are run on a different OS. For example, if the locale of the machine is set to a different language, os errors are translated. So it's a tricky problem generally.

Does that makes sense?

**Comment by matryer** [comment]
`is.Err` could go in, but I do actually think `is.True(err != nil)` is clearer.

**Comment by matejb** [comment]
Yes, testing of error string content is a thing you should not do, except when you should :-)
But I agree that maybe we should not add it to `is` library, people could use it wrongly. 

A bit of background why I suggested it.
It is often the case in applications I'm working on that there are using basic errors, that are all logged in one place and errors do get wrapped with the simple context in various places.
Wrapping is done so that when the error gets written to the log it can be more easily identify it's path of execution eq.
```go
func a()error {
	err := b()
	if err != nil {
		return fmt.Errorf("b failed: %s", err)
	}
}
```
Usually, I would test that this addition of `b failed` is part of the error from `a` when `b` returns an error.

But it is not a problem to have a small wrapper function in my tests that executes `is.True(strings.Contains(err.Error(), "part of error string"))`

**Comment by matryer** [comment]
I know @dahernan is a big user of this package, what does he think?

**Comment by mastertinner** [comment]
I personally chose this package over other assertion libraries for its minimalistic interface and simplicity. I think checking for an error is not a use case which is important enough to increase the API surface of the package. In most cases, you should check for a specific error and use `is.Equal(err, someError)` or `is.Equal(err.Error(), someString)`. Simply checking for the existence of an error doesn't provide much value and I couldn't think of many cases where it would be favorable over checking for a specific error.

**Comment by matejb** [comment]
@mastertinner checking for a specific error is a special case, it notes that the error is fixed, eq. would be io.EOF. Sentinel errors have their place and in certain situations are a good choice. But in my opinion, these are rare.

Checking a full text of the error is something I'm not preferring. It makes test rigid and error-prone. It is often that an additional information will be added to the error resulting in breaking several test. In this situation I go for checking the relevant part of the error, does it contain mention of ID, some other vale etc.

The best approach is to test errors for behavior, is the error eq. temporary:
```
if _, ok := err.(TemporaryError); ok {
//...
}
```
where `TemporaryError` would be an interface.

Nice article on the subject https://dave.cheney.net/2016/04/27/dont-just-check-errors-handle-them-gracefully.

With all said, it is often the case that having error types just for the sake of testing is not necessary. 
If functions are simple, they following SRP and preconditions for an error can be well set up in the test it is sufficient to just check for a presence of an error.

**Comment by matryer** [comment]
Thanks to @matejb but I agree that it's not worth the extra bloat in the package. Testify didn't have such tight controls and [look at the number of things in the package now](https://godoc.org/github.com/stretchr/testify/assert#pkg-index).
