### ISSUE TITLE
Proposal: show var names in output

### ISSUE THREAD

**Issue by v-braun** [matryer/is#23]
It would be cool to have variable names in the output.
Example:

```go
is.Equal(signedin, true) // must be signed in
```

could be rendered like this:

```
is_test.go:175: not true: signedin<false> == true // must be signed in
```

**Comment by matryer** [comment]
I had this same thought. I quite like it. We should see how well the AST stuff works (see https://github.com/matryer/is/pull/24) as this might make it easy.

**Comment by v-braun** [comment]
Will check that out in a new experimental branch.

**Comment by matryer** [comment]
Thanks @v-braun.

While you're there, I wonder how easy it might be to detect _where_ a variable came from, or more specifically _where_ it was last assigned to.

How cool would it be if you would write this:

```go
err := something()
is.NoErr(err)
```

And get a failure that said:

```
err: some error  // from: something()
```

**Comment by v-braun** [comment]
i have built something simmiliar! will push it later.
not exactley your example but is also nice:

``` go
is.NoErr(errors.New("BANG!"))
```

will end in:
```
err: errors.New("BANG!")
```

That is for sure not exactley your example but also very helpfull.

I think the other case is also solvable through AST but is much more complex.
So in theory I have the error *ast.Node* and have only to search the entire AST again for a declaration/assignment to this *ast.Node*.

**Comment by matryer** [comment]
@v-braun This is very cool but I'm not sure the complexity is worth it just yet. I'll review the code more. But I had a thought. Maybe it shouldn't show the code if there is a comment? In theory, if you put a comment, that's what you care about isn't it?

**Comment by j0holo** [comment]
I agree with @matryer, while it is a neat idea this problem can already be solved with a debugger. You know where the test went wrong, put a breakpoint on the function under test and you can inspect each step.
