### ISSUE TITLE
Look for `// ` (with space) not `//` 

### ISSUE THREAD

**Issue by matryer** [matryer/is#3]
Otherwise, URLs appear as comments

**Comment by matryer** [comment]
@dahernan? :)

**Comment by mastertinner** [comment]
@matryer, has this been resolved yet? I'm facing similar errors.

**Comment by breml** [comment]
@matryer Just hit this problem. Can we resolv it by changing the parsing for `// ` (with space) in https://github.com/matryer/is/blob/master/is.go#L283 ?

**Comment by matryer** [comment]
@breml Do you want to have a stab at a fix?
