### ISSUE TITLE
My editor thinks this is bad practice

### ISSUE THREAD

**Issue by tehsphinx** [matryer/is#34]
Hi Mat!

Big fan (of Go of course 😏), long time listener of GoTime and working with Go full time for 4 years next month!

So... I just tried this nice little assert library and the first thing I notice is that my editor thinks I shouldn't do this:

```go
is := is.New(t)
```

It says: `Variable 'is' collides with imported package name` (And I hate to disappoint my editor!)

What is your defence? (Trying to be funny 😂)

**Comment by matryer** [comment]
Fair enough :) In other situations I'd agree with your editor.

For now, just pick a different name:

```
assert := is.New(t)
assert.NoErr(err)
assert.Equal(a, b)
```

**Comment by breml** [comment]
Or import the package with an alias:

```
import iz "github.com/matryer/is"

is := iz.New(t)
```

**Comment by tehsphinx** [comment]
yeah, renaming the package is not really an option any more. I'll close this.

Thx! @matryer, @breml

**Comment by axkirillov** [comment]
Your editor should not take authority over how you write your code. Just disable this inspection.
