### ISSUE TITLE
Ditch the indentation?

### ISSUE THREAD

**Issue by matthewmueller** [matryer/is#44]
Hey there, thanks for creating this package. I use it in all my tests. Would you be open to removing the tab in front? 

The misalignment with other printed logs bugs me a bit (very subjective of course):

<img width="500" alt="CleanShot 2021-09-16 at 21 50 23@2x" src="https://user-images.githubusercontent.com/170299/133716459-89e5adda-5b5d-45d6-afaf-975d890f5684.png">

And with the colors, I think there's enough visual separation:

![image](https://user-images.githubusercontent.com/170299/133716370-600e2219-1ddf-4322-bbce-1f3965e78e0c.png)

If you're up for this change, I'd be happy to open a PR.

**Comment by flowchartsman** [comment]
Thanks for the issue!

Printing test messages with indentation is how `testing.T.Log()` does it, so it's probably best not to deviate from that, especially since a fix for #47 is likely going to involve invoking `t.Log()` directly.
