### ISSUE TITLE
Proposal: custom stacktrace

### ISSUE THREAD

**Issue by alarbada** [matryer/is#58]
While I really like the small and simple API that `is` has, one thing that makes it difficult to use is when developing utilities using is. Let me demonstrate:

```golang
func openDbHelper(is *is.I, dsn string) *sql.DB {
	db, err := sql.Open("mysql", dsn)
	is.NoErr(err) // error while opening database connection

	return db
}

func CreateTestDatabase(is *is.I, dsn string) {
	db := openDbHelper(is, dsn)

	is.NoErr(db.Ping())

	// ...
}
```

Let's say I use openDbHelper at different test functions. If `openDbHelper` fails, I would only see this test output:

```
   test_utils.go:222: failed to open database (or something)
```

This would only show me where the error occurs, but without more context, I end up never knowing exactly how the error happened, because I only have the file - line position of where the error happened, but I don't know who called that test utility.

I'd really enjoy having something like this instead:

```golang

// at testutils.go

func openDbHelper(is *is.I, dsn string) *sql.DB {
	db, err := sql.Open("mysql", dsn)
	is.NoErr(err)

	return db
}

func CreateTestDatabase(is *is.I, dsn string) {
	db := openDbHelper(is.WithFuncCall(), dsn)

	is.NoErr(db.Ping())

	// ...
}

// at somepackage_test.go

func TestSomething(t *testing.T) {
	is := is.New(t)
	CreateTestDatabase(is.WithFuncCall(), "....")
}

```

And, in this hypothetical case, if `TestSomething` failed, you would get this more helpful error output:

```
   test_utils.go:222: failed to open database (or something)
   test_utils.go:(other line): testutils.CreateTestDatabase
   somepackage_test.go:(another line): somepackage.TestSomething
```

This way I immediately know where the error happened, and I don't have to juggle around with `go test -run ...` to check exactly where the error happened.

What do you think?

**Comment by alarbada** [comment]
I've never used the "runtime" package, but I imagine that the `is.WithFuncCall()` would call [runtime.Caller](https://pkg.go.dev/runtime#Caller) or something like this.

**Comment by breml** [comment]
Isn't [`t.Helper()`](https://pkg.go.dev/testing#T.Helper) what you are looking for?

**Comment by ccoVeille** [comment]
> Isn't [`t.Helper()`](https://pkg.go.dev/testing#T.Helper) what you are looking for?

I came to say this, and I'm happy to see someone already did.

**Comment by ccoVeille** [comment]
Here is what you should try @alarbada 

https://pkg.go.dev/github.com/matryer/is#I.Helper

```go
func openDbHelper(is *is.I, dsn string) *sql.DB {
   is.Helper()
   db, err := sql.Open("mysql", dsn)
   is.NoErr(err) // error while opening database connection 	return db
}

func CreateTestDatabase(is *is.I, dsn string) {
    db := openDbHelper(is, dsn)
    is.NoErr(db.Ping())
    // ... 
}
```

And please tell us if it works as requested

**Comment by alarbada** [comment]
Oh yeah, that is exactly what I was looking for, I wasn't aware of `t.Helper()` and this library's equivalent. Thank you so much for pointing me this out @breml @ccoVeille.
