### ISSUE TITLE
Color escape codes break vim

### ISSUE THREAD

**Issue by jhillyerd** [matryer/is#8]
vim can't handle terminal escape codes in compiler/test output, and vim-go does not strip them out.  A failing test is rendered in the Quickfix window as:

    ^[[90mhtml_test.go|14| ^[[39merr: unexpected input^[[32m // should succeed^[[39m

And tries to open a file called `^[[90mhtml_test.go`

**Comment by matryer** [comment]
You can run the tests with `-nocolor` flag to turn off the colouring https://github.com/matryer/is/blob/master/is.go#L77

**Comment by stigok** [comment]
It works as expected in [vim-go](https://github.com/fatih/vim-go) by executing `:GoTest -nocolor`. ([ref](https://github.com/fatih/vim-go/blob/master/doc/vim-go.txt))
